CREATE TABLE person(
    person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(200) UNIQUE NOT NULL,
    year_of_birth int CHECK(year_of_birth >= 1900) NOT NULL
);

CREATE TABLE book(
    book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES person(person_id) ON DELETE SET NULL,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(200) NOT NULL,
    year_of_publish int NOT NULL
)